### ISSUE TITLE
.net core 2.0 changes

### ISSUE THREAD

**Issue by Bogdancev** [ExtCore/ExtCore-Sample-Mvc#1]
Are you going to change startup.cs and program.cs according to .net core 2.0?
They moved content of Startup() constructor to program.cs

**Comment by DmitrySikorsky** [comment]
Yes, after ExtCore 3 is released (now it is beta1). It will be done next week I think. For now you can take a look at ExtCore-Sample project, it is moved to ExtCore 3.0.0-beta1 and .NET Core 2.

**Comment by Bogdancev** [comment]
If you look at the bottom of that file: 
https://github.com/aspnet/MetaPackages/blob/dev/src/Microsoft.AspNetCore/WebHost.cs

It already adds json file, logging and debugging. Would it not be nicer to simplify your code more, something like that:

```
public Startup(IHostingEnvironment hostingEnvironment, IConfiguration configuration)
{
    Configuration = configuration;

    this.extensionsPath = hostingEnvironment.ContentRootPath + Configuration.GetSection("Extensions:Path").Value;
}
```
because the rest was already taken care of.
